image: docker:stable

services:
  - docker:dind

stages:
  - test
  - build
  - push
  - release

test:
  stage: test
  image: 'golang:1.11-stretch'
  tags:
    - docker
    - bloom42cicd
  script:
    - apt update && apt install -y gcc make git
    - make test

build:
  stage: build
  tags:
    - docker
    - bloom42cicd
  script:
    - apk update && apk add make
    - make docker

push:
  stage: push
  only:
    refs:
      - master
  tags:
    - docker
    - bloom42cicd
  script:
    - apk update && apk add make
    - make docker
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - make docker_push


release_docker:
  stage: release
  only:
    - tags
  tags:
    - docker
    - bloom42cicd
  script:
    - apk update && apk add make
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - make docker_release

release_github:
  stage: release
  image: 'golang:1.11-stretch'
  only:
    - tags
  tags:
    - docker
    - bloom42cicd
  script:
    - go get -u github.com/bloom42/rocket
    - rocket
