sudo: required
language: rust
services:
  - docker

rust:
  - 1.33.0

before_install:
  - rustup self update

script:
  - make test
  # - make lint
  - make build
  - make docker_build


before_deploy:
  - export VERSION=$(cat Cargo.toml | grep "version\s=" | cut -d '"' -f2) # for docker provider
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY

deploy:
  - provider: script
    skip_cleanup: true # Important, otherwise the build output would be purged.
    script: make publish
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    on:
      tags: true
  - provider: script
    script: make docker_release
    on:
      tags: true

notifications:
  email:
on_success: never
