[package]
name = "phaser"
version = "0.5.2"
authors = ["z0mbie42 <sylvain@kerkour.com>"]
edition = "2018"
homepage = "https://opensource.bloom.sh/phaser"
repository = "https://github.com/bloom42/phaser.git"
description = "The cloud native security scanner ☁️"
keywords = ["security", "bloom", "phaser", "scanner"]
license-file = "LICENSE.txt"

[dependencies]
# cli args && options parsing
clap = "2.32"
